### ISSUE TITLE
﻿#!/usr/bin/env: No such file or directory

### ISSUE THREAD

**Issue by palbordoy** [Microsoft/appcenter-build-scripts-examples#12]
I'm testing the package name changing script in appcenter, but I get an error
appcenter-pre-build.sh
/Users/vsts/agent/2.136.1/work/1/s/mobileapp/appcenter-pre-build.sh: line 1: ﻿#!/usr/bin/env: No such file or directory

**Comment by ionixjunior** [comment]
Hi @palbordoy, thats weirds, don't makes sense return an error in the first line of the script.

Can you share your script with us?

**Comment by derpixeldan** [comment]
@palbordoy can you exclude an encoding issue for the provided `appcenter-pre-build.sh` file? Have you created it with Windows?

**Comment by palbordoy** [comment]
It was the encodig that was wrong. Changed it to ANSI, and now appcenter is running the script. Anyway, the script is actually not doing anything. I placed it in the project root folder, and added the packagename variable to appcenter. The package name remains the same :(

======================================
Task         : Shell Script
Description  : Run a shell script using bash
Version      : 2.1.3
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613738)
==============================================================================
[command]/bin/bash /Users/vsts/agent/2.136.1/work/1/s/Testapp/appcenter-pre-build.sh
##[section]Finishing: Pre Build Script
##[section]Starting: Build Xamarin.Android project

I was expecting somethink like: "Updating package name to $PACKAGE_NAME in AndroidManifest.xml"
