### ISSUE TITLE
Xamarin change Icon File

### ISSUE THREAD

**Issue by hernandoz** [Microsoft/appcenter-build-scripts-examples#13]
Hi I tried to use Add version name sample to change the icon file on Android configuration  but is not working 
The Android manifest is   
`android:icon="@drawable/icon"`
my script line is , it is finding the file and updating the package name
`sed -i '' 's/icon= "[a-z.@]*"/icon="'$APP_ICON'"/' $MANIFEST`

the error form Appcenter is 
`sed: 1: "s/icon= "[a-z.@]*"/icon ...": bad flag in substitute command: 'i'`

Thanks for your help.

Hernnado

**Comment by ionixjunior** [comment]
Hi @hernandoz, probably your **$APP_ICON** variable contains the / character. Scape this character will solve your problem, e.g.:

`
APP_ICON = @drawable\/custom_icon
`

Another thing, your regex need contain every character your want to replace, so if the default value for icon is `android:icon="@drawable/icon"`, your regex also needs the / character. Dot character is unnecessary in this case.

`
sed -i '' 's/icon="[a-z@/]*"/icon="'$APP_ICON'"/' $MANIFEST
`

I hope this help you!

**Comment by hernandoz** [comment]
Hi @ionixjunior , yes I did change the variable to `APP_ICON = @drawable\/custom_icon`  

and also made some changes to this line using `[[:graph:]]`

> The [[:graph:]] is same as [[:print:]], but matches non-blank characters like alphabets, special characters, numbers but excludes spaces, control characters  etc.

`sed -i '' 's#icon=[[:graph:]]*"#icon="'$APP_ICON'"#' $MANIFEST` 



thanks for your help .
