### ISSUE TITLE
NUnit appcenter-post-build.sh not working

### ISSUE THREAD

**Issue by olidias** [Microsoft/appcenter-build-scripts-examples#18]
Running [the NUnit Test appcenter-post-build.sh](https://github.com/Microsoft/appcenter-build-scripts-examples/blob/master/xamarin/nunit-test/appcenter-post-build.sh) shell script didn't work for my NUnit 3.6.1 Test Project in the Xamarin.Forms Solution. The script greps TestResult.xml for
```
grep -q success="False" $pathOfTestResults
``` 
 which doesn't occur in the output. Changing it to 
```
grep -q 'result="Failed"' $pathOfTestResults
``` 
worked.

**Comment by bruhaha1989** [comment]
#21 should fix this
