### ISSUE TITLE
Temporary fix for build failing after flutter packages get

### ISSUE THREAD

**Issue by sawankumarbundelkhandi** [Microsoft/appcenter-build-scripts-examples#19]
**Running "flutter packages get" in s...**                          
_Because no versions of cached_network_image match >0.4.2 <0.5.0 and cached_network_image >=0.4.1 <0.4.2 depends on flutter_cache_manager ^0.1.1, cached_network_image >=0.4.1 <0.4.2-∞ or >0.4.2 <0.5.0 requires flutter_cache_manager ^0.1.1.
And because flutter_cache_manager >=0.1.0-rc.1 <0.1.2 depends on uuid ^0.5.3 and cached_network_image 0.4.2 depends on flutter_cache_manager ^0.1.2, cached_network_image ^0.4.1 requires uuid ^0.5.3 or flutter_cache_manager ^0.1.2.
Because every version of flutter_test from sdk depends on http 0.12.0 and flutter_cache_manager >=0.1.0-rc.1 depends on http ^0.11.3+14, flutter_test from sdk is incompatible with flutter_cache_manager >=0.1.0-rc.1.
Thus, if flutter_test any from sdk and cached_network_image ^0.4.1 then uuid ^0.5.3.
And because xxx_app depends on uuid ^1.0.3, flutter_test from sdk is incompatible with cached_network_image ^0.4.1.
So, because xxx_app depends on both cached_network_image ^0.4.1 and flutter_test any from sdk, version solving failed._

To fix the issue 
Change the clone branch in post clone script to 

**git clone -b beta https://github.com/flutter/flutter.git**

**Comment by derpixeldan** [comment]
Done. Thanks. Feel free to create PR's the next time.
