### ISSUE TITLE
Expose release notes to scripts

### ISSUE THREAD

**Issue by a-b** [Microsoft/appcenter-build-scripts-examples#20]
Please consider exposing release notes via the environment variable or a text file available for automation.

**Comment by SlavaChernikoff** [comment]
+1. Currently the only way to do it - modify last commit message with 'git commit --ammend'

**Comment by derpixeldan** [comment]
@SlavaChernikoff feel free to add an example script to this repository.

@a-b any feature requests please submit to [our public repo](https://github.com/microsoft/appcenter).

**Comment by dkoprowski** [comment]
@SlavaChernikoff Unfortunatelly it doesn't work any more. I do commit amend in post-clone but release notes are still default.
